/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package thread.complete.listener;

import java.util.Random;

public class App {
    public static void main(String[] args) {
        AppContext appContext = new AppContext();
        for (int i = 98; i < 10000; i++) {
            try {
                Thread.sleep(new Random().nextInt(10000));
                System.out.println("registering client: " + i);
                appContext.registerClientNotification(new Client(i));
            } catch (InterruptedException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
        }
    }
}
